#pragma once
#include <openapi/base/doc.hpp>
#include <openapi/base/holder.hpp>
#include <openapi/base/holder_named.hpp>
#include <openapi/base/named_traits.hpp>
#include <openapi/base/preferences.hpp>
#include <openapi/base/properties/all.hpp>
#include <openapi/base/property_base.hpp>
#include <openapi/base/reflective/all.hpp>
#include <openapi/base/traits/all.hpp>
