BEGIN;

ALTER TABLE timetable_vsu.token DROP CONSTRAINT IF EXISTS user_fk CASCADE;
ALTER TABLE timetable_vsu.token ADD CONSTRAINT user_fk FOREIGN KEY (id_user) REFERENCES timetable_vsu."user" (id) MATCH FULL ON DELETE CASCADE ON UPDATE CASCADE;

COMMIT;
