worker-threads: 4
worker-fs-threads: 2
logger-level: debug

is_testing: true

server-port: 8080

root_login: 'root'
root_password: 'secret-password'

# timetable_vsu_backend_db_1 is the service name + _ + filename of the db_1.sql
dbconnection: 'postgresql://testsuite:password@localhost:15433/timetable_vsu_backend_db_1'
