openapi: 3.0.0
info:
  description: This is a simple timetable API
  version: "1.0.0"
  title: Simple Timetable API
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: admins
    description: Доступно администраторам сервиса
  - name: teachers
    description: Доступны для преподавателей, которые ведут соответствующую группу и соответствующий предмет
  - name: users
    description: Доступно всем
paths:
  /register:
    $ref: 'views/register/view.yaml'
  /login:
    $ref: 'views/login/view.yaml'
  /timetable/get:
    $ref: 'views/timetable/get/view.yaml'
  /admin/create:
    $ref: 'views/admin/create/view.yaml'
  /admin/list:
    $ref: 'views/admin/list/view.yaml'