name: Docker build

'on':
    pull_request:
    push:
        branches:
          - master
          - develop
          - feature/**

jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
            with:
                submodules: true
          - name: Format sources and gen list of them
            run: |
              make gen
              make format-all  
          - name: Check git status
            run: make check-git-status    
          - name: Reuse ccache directory
            uses: actions/cache@v2
            with:
                path: .ccache
                key: 'ccache-dir-${{github.ref}}_run-${{github.run_number}}'
                restore-keys: |
                    ccache-dir-${{github.ref}}_run-
                    ccache-

          - name: Setup ccache
            run: docker-compose run --rm timetable_vsu_backend-container bash -c 'ccache -M 2.0GB && ccache -s'

          - name: Cmake
            run: make docker-cmake-release

          - name: Build
            run: make docker-build-release

          - name: Run tests
            run: make docker-test-release
